baseURL = "https://thecarledwards.com"
title = "The Carl Edwards"
theme = "hugo-theme-m10c"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "Carl Edwards"
  description = "Try → Iterate → Reflect → Learn → Apply → Have Fun!"
  menu_item_separator = " - "
  avatar = "/images/avatar.jpg"
  # Theme colors
  [params.style]
    darkestColor = "#1a2634" # left gutter background color
    darkColor = "#2c3e50" # main content background color
    primaryColor = "#77909d"
    lightColor = "#d6e5f2"
    lightestColor = "#e0da16"

  [[params.social]]
    icon = "brand-github"
    name = "GitHub"
    url = "https://github.com/carledwards"

  [[params.social]]
    icon = "brand-twitter"
    name = "Twitter"
    url = "https://twitter.com/the_CarlEdwards"

  [[params.social]]
    icon = "brand-linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/the-carl-edwards"
